### ISSUE TITLE
가챠 정보 추가

### ISSUE THREAD

**Issue by minding2796** [Team-QSS/KonoPuro-Unity#100]
### Work

가챠 확률 등의 정보를 표기해주세요

### Additional

![image](https://github.com/user-attachments/assets/b21ea237-a815-4a56-8e8c-01dcebbbabb3)

**Comment by dlwlgns268** [comment]
만드는 중입니다. 이미지만 완료되면 추가하도록 하겠습니다.

**Comment by dlwlgns268** [comment]
학생카드 이미지 완성되는대로 완성 가능할 것 같습니다.
