### ISSUE TITLE
1차 수정 요구 사항

### ISSUE THREAD

**Issue by Mooner510** [Team-QSS/KonoPuro-Unity#40]
### Describe

수정 요구 사항이 있습니다. 해당 이슈는 주기적으로 업데이트 될 수 있습니다.

### Work

- [x] UI(버튼)이 어떤 역할을 하는 버튼인지 아이콘 추가
- [x] #58
- [x] #55
- [x] #50
- [x] #42
- [x] #60
- [x] #51

**Comment by AKU430** [comment]
#47 에서 아이콘 추가 완료했습니다
