### ISSUE TITLE
누구나 할 수 있는 할 일 모음

### ISSUE THREAD

**Issue by minding2796** [Team-QSS/KonoPuro-Unity#67]
### Describe

현재 당장 보이는 문제점이나 수정사항을 정리해 보았습니다.
혹시 수정해야할 사항이 있다면 코맨트 부탁드립니다.

### Work

- [x] #68 (MainScene 1, GachaUI, GachaScene, DeckEditTable 등)
- [x] #74
- [x] #77
- [x] #73
- [x] #69
- [x] #71 (리소스 추가)

### Additional

제가 상술한 모든 이슈를 즉시 해결할 수는 없습니다.
본인이 이슈를 해결 할 수 있을것 같으면 작업내용을 각각 이슈로 변환해 해결해 주시면 감사하겠습니다.
이슈를 해결하셨다면 어사인도 한번씩 부탁드립니다.
더 이상 사용하지 않는 씬 삭제의 경우 사용중인 사람이 있을 수 있으니 일정 기간 이후 삭제할 예정입니다.

**Comment by whitefish2n2** [comment]
Todays Card가 하루에 한번씩만 변경되는 기능 구현 <- #62 에서 구현하도록 함

**Comment by minding2796** [comment]
@whitefish2n2 수정되었습니다.
해당 항목이 이슈로 새로 만들어진다면 이슈 링크 변경 예정입니다.

**Comment by whitefish2n2** [comment]
#62 기능의 확장이라 이런 식으로 진행했습니다.

**Comment by minding2796** [comment]
@whitefish2n2 하루에 한번씩 변경될 때 오늘 생성된 카드가 저장될 필요가 없습니다.
랜덤 함수가 있다고 치자면, 그 랜덤 함수에 대해 오늘의 년, 월, 일을 시드로 넣는다면 하루마다 다른 결과값을 얻을 수 있습니다.

**Comment by whitefish2n2** [comment]
그럼그리함-
